Repository soya111/lambda, pull requests merged in 2023-08, with the labels that each got.

#43 Refactoring
  app/webhook/command_handler.go
  cmd/hinatazaka_blog_notifier/main.go
  pkg/blog/hinatazaka_scraper.go
  pkg/infrastructure/dynamodb/diary_repository.go
  pkg/infrastructure/dynamodb/subscriber_repository.go
  pkg/infrastructure/line/client.go
  pkg/infrastructure/line/postback.go
  pkg/model/diary.go
Labels: documentation

#53 Refactor/remove hardcoded table name
  pkg/infrastructure/dynamodb/subscriber_repository.go
Labels: enhancement

#49 bugfix and support command argument
  cmd/hinatazaka_profile/README.md
  cmd/hinatazaka_profile/main.go
  cmd/hinatazaka_profile/main_test.go
Labels: enhancement, good first issue

#50 Feature/local dynamodb init
  Dockerfile
  docker-compose.yaml
  pkg/.env.sample
  pkg/infrastructure/dynamodb/diary_repository_test.go
  pkg/infrastructure/dynamodb/subscriber_repository_test.go
  pkg/model/subscriber.go
  pkg/notifier/README.md
  pkg/notifier/excute_test.go
  scripts/create_tables.go
Labels: enhancement

#55 Feature/follow unfollow join events
  app/webhook/event_handler.go
  pkg/infrastructure/dynamodb/subscriber_repository.go
  pkg/infrastructure/dynamodb/subscriber_repository_test.go
  pkg/model/subscriber.go
Labels: enhancement

#52 Refactor/diary repository
  cmd/hinatazaka_blog_notifier/main.go
  cmd/webhook_receiver/main.go
  pkg/infrastructure/dynamodb/diary_repository.go
  pkg/infrastructure/dynamodb/diary_repository_test.go
  pkg/infrastructure/dynamodb/subscriber_repository.go
  pkg/infrastructure/dynamodb/subscriber_repository_test.go
  pkg/notifier/excute_test.go
  pkg/notifier/notifier.go
Labels: enhancement

#56 Refactor/layered architecture
  app/webhook/command_handler.go
  app/webhook/postback_handler.go
  pkg/infrastructure/dynamodb/diary_repository.go
  pkg/infrastructure/dynamodb/diary_repository_test.go
  pkg/infrastructure/dynamodb/subscriber_repository_test.go
  pkg/model/diary.go
  pkg/notifier/notifier.go
  pkg/service/identity_service.go
  pkg/service/subscription_service.go
Labels: enhancement
